import numpy as np
import planck_low_py

print('- - - - - - - - - - - - - - - - - ')
print('Testing Planck-low-py likelihoods')
print('- - - - - - - - - - - - - - - - - \n')

print('Reading low-ell power spectrum generated by camb...\n')
Cls_2_to_29=np.genfromtxt('data/example_Cl.txt', names=True)

# low-ell temperature log-likelihood from 2 lognormal bins
loglike_low_TT=planck_low_py.planck_lowT_binned_loglike(Cls_2_to_29['TT'])
expected_TT=-11.660801515314658
print('Planck-low-py temperature likelihood:',loglike_low_TT)
print('expected:', expected_TT)
print('difference:', loglike_low_TT-expected_TT, '\n')

# low-ell E-mode polarization log-likelihood from 3 lognormal bins
loglike_low_EE=planck_low_py.planck_lowE_binned_loglike(Cls_2_to_29['EE'])
expected_EE=9.656235151568294
print('Planck-low-py E-mode polarization likelihood:',loglike_low_EE)
print('expected:', expected_EE)
print('difference:', loglike_low_EE-expected_EE, '\n')
